numWidth: 30
numHeight: 16
numMine: 99
cellSize: 33
id2name:
  0: newmedia/cell0.png
  1: newmedia/cell1.png
  2: newmedia/cell2.png
  3: newmedia/cell3.png
  4: newmedia/cell4.png
  5: newmedia/cell5.png
  6: newmedia/cell6.png
  7: newmedia/cell7.png
  8: newmedia/cell8.png
  9: newmedia/blast.png
  10: newmedia/cellup.png
  11: newmedia/cellflag.png
  12: media/prompt.png
  13: newmedia/hover.png
  14: newmedia/celldown.png
